name: exercicio-aula04

on: 
  push:
    branches:
      - feature-new 
  workflow_dispatch:
  schedule:
    - cron: '*/45 * 2-5 * *'
jobs:
 
  JobLinux:
    name: Job Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show README content
      run: cat README.md

    - name: Check Kernel version
      run: uname -r

  JobWindows:
    name: Job Windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print OS version
      run: "Get-CimInstance Win32_OperatingSystem"
